### ISSUE TITLE
オプションが正しく反映されない

### ISSUE THREAD

**Issue by euglenach** [kznrluk/hayaoshi-button-online#7]
![quizbug](https://user-images.githubusercontent.com/28961922/132117921-067e8e6e-f77e-48b2-92ab-28f00c1568cb.gif)

【再現方法】

1. オプションを選択して部屋を作る
2. 名前を入力して早押しボタンの画面に行く
3. ブラウザバックでホームに戻る(ここではオプションが選択されている)
4. 再度部屋を作って早押しボタンの画面に行く
5. オプションが解除されている状態になっている

**Comment by kznrluk** [comment]
下記コミットで修正しました :pray: 
https://github.com/kznrluk/hayaoshi-button-online/commit/50ca6eacc55c2e75d138c8fd90f8e8aa50092172
